//Formulário de Cadastro
package VIEW;

import DAO.AnuncioDAO;
import DTO.AnuncioDTO;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

public class FrmInsertVIEW extends javax.swing.JFrame {

    //Inicializa componentes e chama o método de formatar campos.
    public FrmInsertVIEW() {
        initComponents();
        formatarCampo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        lbAnuncio = new javax.swing.JLabel();
        txtAnuncio = new javax.swing.JTextField();
        lbCliente = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        lbDataInicio = new javax.swing.JLabel();
        lbDataTermino = new javax.swing.JLabel();
        lbInvestimento = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        txtDataInicio = new javax.swing.JFormattedTextField();
        txtDataTermino = new javax.swing.JFormattedTextField();
        txtInvestimento = new javax.swing.JFormattedTextField();
        lbObservacao = new javax.swing.JLabel();
        btnApagar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbTitulo.setText("Cadastrar Anúncio");

        lbAnuncio.setText("*Nome do Anúncio");

        txtAnuncio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnuncioActionPerformed(evt);
            }
        });

        lbCliente.setText("*Cliente");

        lbDataInicio.setText("*Data de Início");

        lbDataTermino.setText("*Data de Término");

        lbInvestimento.setText("*Investimento por Dia");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        lbObservacao.setFont(new java.awt.Font("SansSerif", 0, 8)); // NOI18N
        lbObservacao.setText("*campos obrigatórios");

        btnApagar.setText("Apagar");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAnuncio)
                    .addComponent(txtCliente)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbAnuncio)
                            .addComponent(lbCliente)
                            .addComponent(lbDataInicio)
                            .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDataTermino)
                            .addComponent(txtDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbInvestimento)
                            .addComponent(txtInvestimento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnApagar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbObservacao)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo)
                .addGap(18, 18, 18)
                .addComponent(lbAnuncio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDataInicio)
                    .addComponent(lbDataTermino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbInvestimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInvestimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnApagar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbObservacao)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Método que formata os campos de datas.
    private void formatarCampo() {
        try {
            //Cria o objeto e passa a máscara.
            MaskFormatter mascaraDataIni = new MaskFormatter("##/##/####");
            //Preenche os espaços vazios com o '_' enquanto os dados não forem inseridos. 
            mascaraDataIni.setPlaceholderCharacter('_');
            //Instala a máscara no campo txtData1.
            mascaraDataIni.install(txtDataInicio);
            //Cria o objeto e passa a máscara.
            MaskFormatter mascaraDataFim = new MaskFormatter("##/##/####");
            //Cria o objeto e passa a máscara.
            mascaraDataFim.setPlaceholderCharacter('_');
            //Instala a máscara no campo txtData1.
            mascaraDataFim.install(txtDataTermino);

        } catch (ParseException erro) {
            //Exibe uma janela com o erro gerado.
            JOptionPane.showMessageDialog(null, "Erro ao formatar campo de texto: " + erro, "Erro", JOptionPane.ERROR);
        }
    }


    private void txtAnuncioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnuncioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnuncioActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        //Cria as variáveis.
        String anuncio, nome, dt_ini, dt_fim, vl_invst, diaInicio, mesInicio, anoInicio, diaFim, mesFim, anoFim;
        //Recebe os dados do usuário.
        anuncio = txtAnuncio.getText();
        nome = txtCliente.getText();
        //Formata as entradas de data para o padrão usado no sql
        diaInicio = txtDataInicio.getText().substring(0, 2);
        mesInicio = txtDataInicio.getText().substring(3, 5);
        anoInicio = txtDataInicio.getText().substring(6);
        dt_ini = anoInicio + "-" + mesInicio + "-" + diaInicio;
        diaFim = txtDataTermino.getText().substring(0, 2);
        mesFim = txtDataTermino.getText().substring(3, 5);
        anoFim = txtDataTermino.getText().substring(6);
        dt_fim = anoFim + "-" + mesFim + "-" + diaFim;
        vl_invst = txtInvestimento.getText();
        //Passa os dados para a DTO.
        AnuncioDTO objanunciodto = new AnuncioDTO();
        objanunciodto.setNO_ANUNC(anuncio);
        objanunciodto.setNO_CLIENTE(nome);
        objanunciodto.setDT_INIC(dt_ini);
        objanunciodto.setDT_TERM(dt_fim);
        objanunciodto.setVL_INVST_DIA(vl_invst);
        //Chama o método de cadastro na DAO.
        AnuncioDAO objanunciodao = new AnuncioDAO();
        objanunciodao.cadastrarAnuncio(objanunciodto);
        //Limpa os campos.
        limpaCampos();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        limpaCampos();
    }//GEN-LAST:event_btnApagarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        //Abre o formulário de menu e fecha o formulário atual caso o botão 'btnVoltar' tenha sido acionado.
        new FrmMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInsertVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInsertVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInsertVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInsertVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInsertVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lbAnuncio;
    private javax.swing.JLabel lbCliente;
    private javax.swing.JLabel lbDataInicio;
    private javax.swing.JLabel lbDataTermino;
    private javax.swing.JLabel lbInvestimento;
    private javax.swing.JLabel lbObservacao;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField txtAnuncio;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JFormattedTextField txtDataInicio;
    private javax.swing.JFormattedTextField txtDataTermino;
    private javax.swing.JFormattedTextField txtInvestimento;
    // End of variables declaration//GEN-END:variables

    //Limpa os campos.
    public void limpaCampos() {
        txtAnuncio.setText("");
        txtCliente.setText("");
        txtDataInicio.setText("");
        txtDataTermino.setText("");
        txtInvestimento.setText("");
    }
}
